# Generated by Django 3.2.16 on 2023-09-13 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 19, 59, 41, 904776), null=True, verbose_name='Дата'),
        ),
    ]
